version: '3.8'

services:
  tennis:
    build:
      context: .      # путь к директории, где находится Dockerfile
    image: tennis:latest
    container_name: tennis_container
    ports:
      - "8000:8000"
    restart: unless-stopped

    volumes:
      - ./db:/app/db
      - static_volume:/app/staticfiles

  nginx:
    image: nginx:latest
    container_name: nginx_tennis
    ports:
      - "80:80"
    volumes:
      - static_volume:/app/staticfiles
      - ./nginx.conf:/etc/nginx/nginx.conf:ro

volumes:
  static_volume:
