version: '3.8'

services:
  tennis:
    build:
      context: .      # путь к директории, где находится Dockerfile
    image: tennis:latest
    container_name: tennis_container
    ports:
      - "8000:8000"
    restart: unless-stopped

    volumes:
      - ./db:/app/db
