# Generated by Django 5.1.7 on 2025-03-26 14:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Club',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Название клуба')),
            ],
            options={
                'verbose_name': 'Клуб',
                'verbose_name_plural': 'Клубы',
            },
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('played_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата проведения')),
            ],
            options={
                'verbose_name': 'Матч',
                'verbose_name_plural': 'Матчи',
            },
        ),
        migrations.CreateModel(
            name='ClubEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название события')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('date', models.DateTimeField(verbose_name='Дата и время проведения')),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tennis_app.club', verbose_name='Клуб')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Создатель')),
            ],
            options={
                'verbose_name': 'Событие клуба',
                'verbose_name_plural': 'События клуба',
            },
        ),
        migrations.CreateModel(
            name='FriendlyGame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('played_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата проведения')),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tennis_app.club', verbose_name='Клуб')),
            ],
            options={
                'verbose_name': 'Свободная игра',
                'verbose_name_plural': 'Свободные игры',
            },
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('start_time', models.DateTimeField(blank=True, null=True, verbose_name='Начало')),
                ('end_time', models.DateTimeField(blank=True, null=True, verbose_name='Окончание')),
                ('score_player1', models.PositiveIntegerField(default=0, verbose_name='Очки игрока 1')),
                ('score_player2', models.PositiveIntegerField(default=0, verbose_name='Очки игрока 2')),
                ('friendly', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='games', to='tennis_app.friendlygame', verbose_name='Свободная игра')),
                ('match', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='games', to='tennis_app.match', verbose_name='Матч')),
            ],
            options={
                'verbose_name': 'Партия',
                'verbose_name_plural': 'Партии',
            },
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100, verbose_name='ФИО')),
                ('joined_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата вступления')),
                ('rating', models.IntegerField(default=1000, verbose_name='Рейтинг')),
                ('dominant_hand', models.CharField(choices=[('right', 'Правая'), ('left', 'Левая')], default='right', max_length=10, verbose_name='Преобладающая рука')),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tennis_app.club', verbose_name='Клуб')),
            ],
            options={
                'verbose_name': 'Игрок',
                'verbose_name_plural': 'Игроки',
            },
        ),
        migrations.AddField(
            model_name='match',
            name='player1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches_as_player1', to='tennis_app.player', verbose_name='Игрок 1'),
        ),
        migrations.AddField(
            model_name='match',
            name='player2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches_as_player2', to='tennis_app.player', verbose_name='Игрок 2'),
        ),
        migrations.AddField(
            model_name='match',
            name='winner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wins', to='tennis_app.player', verbose_name='Победитель'),
        ),
        migrations.AddField(
            model_name='friendlygame',
            name='player1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='friendlies_as_player1', to='tennis_app.player', verbose_name='Игрок 1'),
        ),
        migrations.AddField(
            model_name='friendlygame',
            name='player2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='friendlies_as_player2', to='tennis_app.player', verbose_name='Игрок 2'),
        ),
        migrations.AddField(
            model_name='friendlygame',
            name='winner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='friendly_wins', to='tennis_app.player', verbose_name='Победитель'),
        ),
        migrations.CreateModel(
            name='Point',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Время')),
                ('order', models.PositiveIntegerField(verbose_name='Порядок')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='points', to='tennis_app.game', verbose_name='Партия')),
                ('scored_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tennis_app.player', verbose_name='Игрок, набравший очко')),
            ],
            options={
                'verbose_name': 'Очко',
                'verbose_name_plural': 'Очки',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название турнира')),
                ('start_date', models.DateField(verbose_name='Дата начала')),
                ('is_round_robin', models.BooleanField(default=True, verbose_name='Круговой турнир')),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tennis_app.club', verbose_name='Клуб')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Создатель')),
            ],
            options={
                'verbose_name': 'Турнир',
                'verbose_name_plural': 'Турниры',
            },
        ),
        migrations.AddField(
            model_name='match',
            name='tournament',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='tennis_app.tournament', verbose_name='Турнир'),
        ),
        migrations.CreateModel(
            name='ClubAdmin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_at', models.DateTimeField(auto_now_add=True, verbose_name='Назначен')),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tennis_app.club', verbose_name='Клуб')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Администратор клуба',
                'verbose_name_plural': 'Администраторы клуба',
                'unique_together': {('user', 'club')},
            },
        ),
        migrations.CreateModel(
            name='ClubMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tennis_app.club', verbose_name='Клуб')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Член клуба',
                'verbose_name_plural': 'Члены клуба',
                'unique_together': {('user', 'club')},
            },
        ),
        migrations.CreateModel(
            name='Standing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.IntegerField(default=0, verbose_name='Очки')),
                ('rank', models.IntegerField(default=0, verbose_name='Место')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tennis_app.player', verbose_name='Игрок')),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='standings', to='tennis_app.tournament', verbose_name='Турнир')),
            ],
            options={
                'verbose_name': 'Турнирная таблица',
                'verbose_name_plural': 'Турнирные таблицы',
                'unique_together': {('tournament', 'player')},
            },
        ),
    ]
