# Generated by Django 5.1.7 on 2025-08-18 14:15

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tennis_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='match',
            options={'ordering': ['round_number', 'bracket_position', 'id'], 'verbose_name': 'Матч', 'verbose_name_plural': 'Матчи'},
        ),
        migrations.RemoveField(
            model_name='tournament',
            name='is_round_robin',
        ),
        migrations.AddField(
            model_name='match',
            name='bracket_position',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Позиция в раунде'),
        ),
        migrations.AddField(
            model_name='match',
            name='next_match',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='previous_matches', to='tennis_app.match', verbose_name='Следующий матч'),
        ),
        migrations.AddField(
            model_name='match',
            name='round_number',
            field=models.PositiveIntegerField(default=1, verbose_name='Раунд'),
        ),
        migrations.AddField(
            model_name='tournament',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Создан'),
        ),
        migrations.AddField(
            model_name='tournament',
            name='tournament_type',
            field=models.CharField(choices=[('round_robin', 'Круговой'), ('elimination', 'Олимпийка')], default='round_robin', max_length=20, verbose_name='Тип турнира'),
        ),
        migrations.AlterField(
            model_name='match',
            name='player1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matches_as_player1', to='tennis_app.player', verbose_name='Игрок 1'),
        ),
        migrations.AlterField(
            model_name='match',
            name='player2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matches_as_player2', to='tennis_app.player', verbose_name='Игрок 2'),
        ),
        migrations.CreateModel(
            name='ClubAdminInvite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, verbose_name='Email приглашенного')),
                ('token', models.CharField(editable=False, max_length=64, unique=True, verbose_name='Токен')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('accepted_at', models.DateTimeField(blank=True, null=True, verbose_name='Принято')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
                ('expires_at', models.DateTimeField(blank=True, null=True, verbose_name='Истекает')),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admin_invites', to='tennis_app.club', verbose_name='Клуб')),
                ('invited_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Пригласил')),
            ],
            options={
                'verbose_name': 'Приглашение администратора',
                'verbose_name_plural': 'Приглашения администраторов',
                'indexes': [models.Index(fields=['token'], name='tennis_app__token_51f487_idx')],
            },
        ),
        migrations.CreateModel(
            name='TournamentParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seed', models.PositiveIntegerField(default=0, verbose_name='Посев')),
                ('joined_at', models.DateTimeField(auto_now_add=True, verbose_name='Добавлен')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tennis_app.player', verbose_name='Игрок')),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants_links', to='tennis_app.tournament', verbose_name='Турнир')),
            ],
            options={
                'verbose_name': 'Участник турнира',
                'verbose_name_plural': 'Участники турнира',
                'ordering': ['seed', 'id'],
                'unique_together': {('tournament', 'player')},
            },
        ),
    ]
