# Generated by Django 5.1.7 on 2025-08-18 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tennis_app', '0002_alter_match_options_remove_tournament_is_round_robin_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='finished',
            field=models.BooleanField(default=False, verbose_name='Завершен'),
        ),
        migrations.AddField(
            model_name='match',
            name='sets_player1',
            field=models.PositiveIntegerField(default=0, verbose_name='Сеты игрока 1'),
        ),
        migrations.AddField(
            model_name='match',
            name='sets_player2',
            field=models.PositiveIntegerField(default=0, verbose_name='Сеты игрока 2'),
        ),
    ]
