# Generated by Django 5.1.7 on 2025-08-18 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tennis_app', '0003_match_finished_match_sets_player1_match_sets_player2'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='first_server',
            field=models.PositiveIntegerField(choices=[(1, 'Игрок 1'), (2, 'Игрок 2')], default=1, verbose_name='Первый подающий'),
        ),
    ]
