# Generated by Django 5.1.7 on 2025-09-09 08:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tennis_app', '0005_friendlygame_doubles_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='friendlygame',
            name='recorded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Записал результат'),
        ),
        migrations.AddField(
            model_name='friendlygame',
            name='score_team1',
            field=models.PositiveIntegerField(default=0, verbose_name='Счет команды 1'),
        ),
        migrations.AddField(
            model_name='friendlygame',
            name='score_team2',
            field=models.PositiveIntegerField(default=0, verbose_name='Счет команды 2'),
        ),
    ]
